"""init migration

Revision ID: 698269228b79
Revises: 
Create Date: 2026-09-05 19:16:35.672466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698269228b79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('family_status', sa.String(length=20), nullable=True),
    sa.Column('student_status', sa.String(length=30), nullable=True),
    sa.Column('student_course', sa.String(length=30), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('self_employed', sa.Boolean(), nullable=True),
    sa.Column('income_frequency', sa.String(length=30), nullable=True),
    sa.Column('income_source', sa.String(length=30), nullable=True),
    sa.Column('income_source_other', sa.String(length=255), nullable=True),
    sa.Column('credit_history', sa.String(length=30), nullable=True),
    sa.Column('payment_overdue', sa.String(length=30), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_method_other', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_subscription',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subscription_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscription')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
