"""Added session field in user model

Revision ID: 75d73a70c171
Revises: a8b1c4c88534
Create Date: 2026-09-06 14:59:50.247524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d73a70c171'
down_revision: Union[str, Sequence[str], None] = 'a8b1c4c88534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_session',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_account_session_expires_at'), 'account_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_account_session_token_hash'), 'account_session', ['token_hash'], unique=True)
    op.create_index(op.f('ix_account_session_user_id'), 'account_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_session_user_id'), table_name='account_session')
    op.drop_index(op.f('ix_account_session_token_hash'), table_name='account_session')
    op.drop_index(op.f('ix_account_session_expires_at'), table_name='account_session')
    op.drop_table('account_session')
    # ### end Alembic commands ###
