"""Fix null

Revision ID: a62663e997ab
Revises: 75d73a70c171
Create Date: 2026-09-06 15:05:19.927912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62663e997ab'
down_revision: Union[str, Sequence[str], None] = '75d73a70c171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user_profile', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user_profile', 'patronymic',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user_profile', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user_profile', 'patronymic',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user_profile', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user_profile', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
