"""Added session

Revision ID: a8b1c4c88534
Revises: 698269228b79
Create Date: 2026-09-06 14:52:41.602000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b1c4c88534'
down_revision: Union[str, Sequence[str], None] = '698269228b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('user_profile', sa.Column('is_ended', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'is_ended')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
