"""Fix null again

Revision ID: deada5ba823d
Revises: a62663e997ab
Create Date: 2026-09-06 15:06:38.493055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deada5ba823d'
down_revision: Union[str, Sequence[str], None] = 'a62663e997ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_profile', 'city',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'city',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user_profile', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
